### ISSUE TITLE
Getting MODULE_NOT_FOUND when using on function with Layer

### ISSUE THREAD

**Issue by ea-tal** [FidelLimited/serverless-plugin-optimize#102]
I am trying to use this plugin with a configuration that ran Instana ( a monitoring system) 
their deployment uses layer an should be implemented like this: 

```
functions:
    index:
        handler: 'instana-aws-lambda-auto-wrap.handler'
        environment:
            LAMBDA_HANDLER: 'dist/index.handler'
        events:
            - http:
                  method: get
                  path: /hi
        layers:
            - arn:aws:lambda:us-east-1:410797082306:layer:instana-nodejs:30
```

When I deploy the configuration, It tries to optimize "instana-aws-lambda-auto-wrap.handler"  and I get MODULE_NOT_FOUND
