### ISSUE TITLE
how do you install external dependencies?

### ISSUE THREAD

**Issue by JaredAAT** [FidelLimited/serverless-plugin-optimize#118]
when looking at this part of the documentation:

> external Array of modules to be copied into node_modules instead of being loaded into browserify bundle. Note that external modules will require it's dependencies within it's directory. (cd external_modules/some-module && npm i --prod)

given a serverless.yml of: 

```
functions:
  resultpdf:
      handler: handler.resultPDF
      runtime: nodejs12.x
      timeout: 20
      memorySize: 1600
      optimize:
        external: ["chrome-aws-lambda"]
```

how do you go about running `cd external_modules/schrome-aws-lambda && npm i --prod`?

**Comment by alecmcgovern** [comment]
@JaredAAT did you ever figure this out?  I'm working with the same package `chrome-aws-lambda` and struggling to include all its dependencies.

**Comment by alecmcgovern** [comment]
If anyone else runs into this, the solution is to `cd` into your `node_modules` in the root of your project and run the install command.  This way all the dependencies are included when the `external` packages are copied over to the optimized build.  I added a `postinstall` command to my `package.json` so I didn't have to think about running this anytime the repo was cloned or my packages were re-installed.

Note: I also needed to include `puppeteer-core` in the external packages, and do a similar production install for that package.

serverless.yml
```
  functionName:
    handler: functions/index.handler
    optimize:
      external: ['chrome-aws-lambda', 'puppeteer-core']
```

package.json
```
  "scripts": {
    ...
    "postinstall": "yarn run install:chrome-aws-lambda && yarn run install:puppeteer",
    "install:chrome-aws-lambda": "cd node_modules/chrome-aws-lambda && npm i --production",
    "install:puppeteer": "cd node_modules/puppeteer-core && npm i --production",
  },
```
